### ISSUE TITLE
thoughts?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/IrrationalConstants.jl#1]

**Comment by torfjelde** [comment]
I'll leave defining concrete rules/guidelines about what should and shouldn't go in this package to you people who actually know what you're talking about here:)

But I can give some examples of which ones I'm personally thinking about and my motivation behind it.

As mentioned on Slack, there several reasons why having such constants gather in a single package, e.g.
- SpecialFunctions.jl computes many of these constants as intermediate variables in several places, thus having to perform explicit conversions to the desired precision, e.g. https://github.com/JuliaMath/SpecialFunctions.jl/blob/d24f19ea0549f12f8c77a8d7ccbef4413edb4836/src/erf.jl#L442. Instead we can use some of these constants in their place, and just let promotion do it's thing.
- Because there already are some irrationals provided in `Base`, people are using already using such constants in their computations, e.g. `π` is a prolific one. But because there are so few it often means that one often has to either: a) rewrite a computation to ensure one does not accidentally convert the `Irrational` into a `Float64`, which in turn means that any `Float32` present in the rest of the computation is promoted to `Float64`, b) insert explicit conversions everywhere. Both of these means that one might have to sacrifice numerical accuracy to ensure that the return-type makes sense. And in practice, it's often the case we forget to do such things, e.g. many of the diff-rules for SpecialFunctions.jl (both those for ChainRulesCore.jl present in SpecialFunctionsjl and those present in DiffRules.jl) will "silently" convert the dual to `Float64` even if both the input and the primal is `Float32`, simply due to the ordering of the computations https://github.com/JuliaDiff/DiffRules.jl/pull/55 . I'd argue that such bugs are more plentiful than if we actually had access to some more convenient constants.

**Comment by dpsanders** [comment]
I suggest making a list of possible constants to include that can be discussed.

**Comment by devmotion** [comment]
My suggestion would be to include all constants that are exported by StatsFuns: https://github.com/JuliaStats/StatsFuns.jl#constants (the log constants are actually defined in LogExpFunctions nowadays and only reexported by StatsFuns)

**Comment by torfjelde** [comment]
> My suggestion would be to include all constants that are exported by StatsFuns: https://github.com/JuliaStats/StatsFuns.jl#constants (the log constants are actually defined in LogExpFunctions nowadays and only reexported by StatsFuns)

I thought I linked this in my comment, but I accidentally lost it when copy-pasting my comment! So I second this suggestion :+1: 
Just for reference:
- `twoπ`: 2π
- `fourπ`: 4π
- `halfπ`: π / 2
- `quartπ`: π / 4
- `invπ`: 1 / π
- `twoinvπ`: 2 / π
- `fourinvπ`: 4 / π
- `inv2π`: 1 / (2π)
- `inv4π`: 1 / (4π)
- `sqrt2` : √2
- `sqrt3` : √3
- `sqrtπ`: √π
- `sqrt2π`: √(2π)
- `sqrt4π`: √(4π)
- `sqrthalfπ`: √(π / 2)
- `invsqrt2` : 1 / √2
- `invsqrt2π`: 1 / √(2π)
- `loghalf` : log(1 / 2)
- `logtwo` : log(2)
- `logπ`: log(π)
- `log2π`: log(2π)
- `log4π`: log(4π)

**Comment by dlfivefifty** [comment]
I often have wished for:

• `One`: 1
• `Zero`: 0

**Comment by devmotion** [comment]
> I often have wished for:
> 
> • `One`: 1
> • `Zero`: 0

In the general sense of `ZeroType` and `OneType` in https://github.com/JuliaFolds/InitialValues.jl as identity element for addition and multiplication, not restricted to integers?

**Comment by dlfivefifty** [comment]
No, the real (integer) number `1`, but known at compile time. So that I can, for example, convert
```julia
(One() - x)^a * (One() + x)^b
```
to `JacobiWeight(a,b)`. Also `UnitInterval()` could be replaced by `Zero()..One()`. I guess I'd also need a `MinusOne()` to replace `ChebyshevInterval()` with `-One()..One()`.


I think I also had some special cases in broadcasting where `Zero()` may have been useful.

But it's not really critical.

**Comment by dpsanders** [comment]
@dlfivefifty How would you detect that you can do that conversion? Can you make use of Symbolics.jl here?

**Comment by dlfivefifty** [comment]
The code would look something like this:
```julia
x = Inclusion(-One()..One())
w = (x .+ One()).^a .* (One() .- x).^b
```
This case is a bit artificial of course, since just saying `w = JacobiWeight(a, b)` is clearer. But there are other cases where one might want to do singularity detection at compile time. E.g. one might want to auto-singularity-detect the following:
```julia
x = Inclusion(Zero()..One())
sin.(sqrt.(x)) # recognise that this is sqrt(x) * something smooth at compiule time
```

**Comment by JeffreySarnoff** [comment]
for these constants: Pi, Euler's, Catalan's, Khinchin’s, Glaisher’s, Apery’s.
[Arb's algorithms for mathematical constants](https://arblib.org/constants.html?highlight=constants)

**Comment by torfjelde** [comment]
> The code would look something like this

Though this actually looks kind of neat, it's very different from what I had in mind. I meant just straight up `Irrational` that are commonly used, for which a common dependency could simplify and improve a lot of code in downstream packages, e.g. SpecialFunctions.jl, DiffRules.jl, etc.

With that being said, I wouldn't be opposed to having more niceties in here!

**Comment by dlfivefifty** [comment]
That code would be in a different package. The only thing here would be constants `One` and `Zero`

**Comment by JeffreySarnoff** [comment]
I have often wanted (yes, I can add)
• Two: 2

**Comment by dlfivefifty** [comment]
How about
```julia
struct SInteger{K} <: Integer end
promote_rule(::Type{<:SInteger}, ::Type{Int}) = Int
Int(::SInteger{K}) where K = K

const One = SInteger{1}
const Zero = SInteger{0}

for op in (:*, :+, :-)
    @eval *(::SInteger{K}, ::SInteger{J}) where {K,J} = SInteger{K*J}() # probably should be @generated...
end
```

So that this works:
```julia
julia> One()Zero()
Zero()

julia> One()One()
One()

julia> One() + 2
3

julia> SInteger{2}() + 2
4
```


(I think `const Two = SInteger{2}` seems a step too far...)

**Comment by devmotion** [comment]
I am a bit sceptical, to me it seems this is quite different from what I had in mind (and @torfjelde as well, I guess?) and would be heavier and more complicated and cover a different use case. Also, it seems this is already covered by different packages such as Static.jl and StaticNumbers.jl.

**Comment by devmotion** [comment]
So I guess the name `IrrationalConstants.jl` would capture more accurately what I had in mind.

**Comment by dlfivefifty** [comment]
Ah I didn't know about StaticNumbers.jl, in which case you are right.

I agree with the name IrrationalConstants.jl, as the type in Julia is now called `Irrational`.

**Comment by JeffreySarnoff** [comment]
I agree with the original focus --
changing the name to IrrationalConstants.jl

**Comment by JeffreySarnoff** [comment]
Lyndon White suggests [Mosè Giordano's PhysicalConstants](https://github.com/JuliaPhysics/PhysicalConstants.jl) may suggest approaches -- ignoring the Unitfuls.

**Comment by giordano** [comment]
`PhysicalConstants.jl` uses exactly the same approach as `Irrational` in `Base`, which is to have a singleton for each constant and define a bunch of methods for each of them.  Frankly, in hindsight I'm not overly happy about this approach, I may change how constants are defined in the future to have a more structured data type, instead of dozens of singletons.

The fact is that while it's cool to have lots of information at compile-time to speed-up runtime, you're also going to make compile-time increase quite noticeably, which is what it's warned against by the section [The dangers of abusing multiple dispatch](https://docs.julialang.org/en/v1/manual/performance-tips/#The-dangers-of-abusing-multiple-dispatch-(aka,-more-on-types-with-values-as-parameters)) of the manual.  In the case of `PhysicalConstants` the increase of compile time is mostly needless: I don't even define special arithmetic/algebraic methods for those constants because I don't need to, so runtime is not going to be sped up in any sensible way, and large compile time is what most users are going to notice first and will be most annoyed by.  Just showing a `PhysicalConstant` for the first time takes 1-2 seconds, it's really not great.

**Comment by devmotion** [comment]
I made a PR with the StatsFuns constants: https://github.com/JuliaMath/IrrationalConstants.jl/pull/3

**Comment by devmotion** [comment]
Maybe the package is ready for an initial release?

**Comment by dlfivefifty** [comment]
Need to decide on whether to rename Irrationals.jl https://github.com/JuliaMath/IrrationalConstants.jl/issues/4

**Comment by devmotion** [comment]
I still think that the name IrrationalConstants.jl is more suitable, it describes more clearly that the package deals with constants and not with e.g. general calculations with irrational numbers.

**Comment by dlfivefifty** [comment]
I would argue Irrationals.jl implies it deals with instances of `Irrational`

**Comment by devmotion** [comment]
One could also define and work with other subtypes of `AbstractIrrational` (which do not even have to be irrational by the way :eyes: https://github.com/JuliaLang/julia/blob/e35028acd307db6c33cf857c5faa1da497d197ad/base/irrationals.jl#L5-L19).

**Comment by dlfivefifty** [comment]
ok point taken

**Comment by JeffreySarnoff** [comment]
preparing to register this

**Comment by devmotion** [comment]
Package is registered and used throughout the ecosystem, so I guess this issue can be closed.
